### ISSUE TITLE
403 Forbidden issue when trying to access pretrained models on s3

### ISSUE THREAD

**Issue by KOD1S** [SindiLab/ACTIVA#6]
Hi,

I am running into a 403 forbidden access issue when trying to perform wget on the pretrained models. Has your public access permission key expired on this bucket? Screenshot below:

![Screenshot from 2022-06-15 11-57-18](https://user-images.githubusercontent.com/63750985/173813106-0b39608c-8c28-4f39-be1c-693f9d468c26.png)

**Comment by dr-aheydari** [comment]
Hi @KOD1S ,

So sorry for my late response and my apologies for the S3 issue. I could be wrong, but I believe you need to use the URL of the object as opposed to the S3 URI for `wget` (check out [this post](https://stackoverflow.com/questions/18239567/how-can-i-download-a-file-from-an-s3-bucket-with-wget) for more info). Alternatively, one could use Amazon CLI (e.g. `s3 cp`) for data transfer.

Please give these URLs a try and let me know if any other issues arise (or if the same one persists):

**68K Model**: https://activa-material.s3.us-west-2.amazonaws.com/Model-Weights/68K+PBMC/ACTIVA_68kPBMC.pth 

**Brain Small**: https://activa-material.s3.us-west-2.amazonaws.com/Model-Weights/20K+Brain+Small/ACTIVA_BrainSamll.pth

Hope this helped!
Ali

**Comment by KOD1S** [comment]
Hi Ali,

Fantastic, those download links work - thank you so much :)

Richard

**Comment by KOD1S** [comment]
One more request - do you have the stats for the training of these models? I.e. the number of epochs?

**Comment by dr-aheydari** [comment]
Hi @KOD1S,

I'm glad it worked for you! And I believe the models are saved as a `dict`, where there exists a key named `epoch` that shows which epoch the model was saved. We also describe the training scheme in our paper as well : ) 

I'm closing this issue (since the download was fixed), but please feel free to open another issue with any questions you may have!

**Comment by KOD1S** [comment]
Thanks again Ali, much appreciated!

**Comment by varshak97** [comment]
Hi @dr-aheydari,

Thank you for posting the pre-trained model URLs here, they're working! 
But, I tried downloading the **post-processed data** the same way, they're still not working. These are the links I tried: 
Brain small: https://activa-material.s3.us-west-2.amazonaws.com/PostProcessedData/final_brainsmall_val_int_clust.h5ad
68k pbmc: https://activa-material.s3.us-west-2.amazonaws.com/PostProcessedData/final_68kpbmc_val_int_clust.h5ad

<img width="872" alt="image" src="https://user-images.githubusercontent.com/54019108/180878461-54fe1e57-c96a-472d-994a-ef5de178e64b.png">

Please suggest a way to download them, thank you!

**Comment by dr-aheydari** [comment]
Hi @varshak97,

Thank you for checking out ACTIVA, and sorry for the trouble.

Are you using AWS CLI? (I don't think it should be an issue if you are utilizing AWS CLI). However, if you are running into issues with CLI, or if you would like more help with data access, please feel free to open a new issue and I'd be happy to discuss it there : ) 

Please let me know if you have any additional questions/comment!
